# This file sets the configuration of the 'Article' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        # the configuration of this entity is very verbose because it's used as
        # an example to show all the configuration options available for entities
        # check out the configuration of the other entities to see how concise
        # can be the configuration of your backend
        Article:
            class: App\Entity\Article
            title: '%%entity_label%%'
            actions:
                - { name: 'show', label: 'show', icon: 'search' }
                - { name: 'edit', label: 'edit', icon: 'edit' }
                - { name: 'delete', label: 'delete', icon: 'trash' }
            show:
                fields:
                    - 'id'
                    - 'name'
                    - { property: 'content', type: 'raw' }
                    - 'releaseAt'
                    - 'updatedAt'
            list:
                fields:
                    - 'id'
                    - 'name'
                    - { property: 'type', label: '私有模式' }
                    - { property: 'isUp', label: '是否置顶' }
                    - { property: 'isSupport', label: '是否推荐' }
                    - { property: 'categories',label: '所属栏目' }
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-8', label: '主要信息', icon: 'pencil' }
                    - { property: 'name', css_class: 'large' }
                    - { property: 'content', id: 'editor', type: 'textarea' }
                    - { type: 'divider' }
                    - { property: 'categories', type: 'easyadmin_autocomplete' }
                    - { type: 'group', css_class: 'col-sm-4', label: '文章设置', icon: 'cube' }
                    - { property: 'isUp', help: '是否置顶.' }
                    - { property: 'isSupport', help: '是否推荐.' }
                    - { property: 'type', help: '是否可见.',label: '是否可见',}
                    - { property: 'releaseAt',css_class: 'col-sm-12', }
