# This file sets the configuration of the 'Article' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    list:
        actions: ['show','edit', 'search', 'delete']
    entities:
        # the configuration of this entity is very verbose because it's used as
        # an example to show all the configuration options available for entities
        # check out the configuration of the other entities to see how concise
        # can be the configuration of your backend
        Comment:
            class: App\Entity\Comment
            title: '%%entity_label%%'
            actions:
                - { name: 'show', icon: 'search' }
                - { name: 'edit', label: 'edit', icon: 'edit' }
                - { name: 'delete', label: 'delete', icon: 'trash' }
            show:
                title: '%%entity_label%% (#%%entity_id%%)'
                fields:
                    - 'id'
                    - 'article'
                    - { property: 'content', type: 'raw' }
                    - 'user'
                    - 'type'
                    - 'createdAt'
            list:
                fields:
                    - 'id'
                    - { property: 'article', label: '文章' }
                    - { property: 'user', label: '评论人' }
                    - { property: 'type', label: '隐私留言' }
                    - { property: 'createdAt',label: '创建时间' }
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-8', label: '主要信息', icon: 'pencil' }
                    - { property: 'article'}
                    - { property: 'content', type: 'textarea' }
                    - { property: 'parent' }
                    - { type: 'divider' }
                    - { property: 'user', type: 'easyadmin_autocomplete' }
                    - { type: 'group', css_class: 'col-sm-4', label: '留言设置', icon: 'cube' }
                    - { property: 'type', label: '仅博主可见' }
                actions:
