easy_admin:
    site_name: '%env(SITE_NAME)%'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
        number: '%.2f'
    design:
            brand_color: '#343A40'
            color_scheme: 'light'
            rtl: false
    entities:
        Product:
          # List the entity class name you want to manage
          class: App\Entity\Product
          help: 'This is product list'
        User:
          # List the entity class name you want to manage
          class: App\Entity\User
