vich_uploader:
    db_driver: orm
    mappings:
        article_image:
            uri_prefix: '%app.path.article_images%'
            upload_destination: '%kernel.root_dir%/../public/uploads/images/articles'