easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    prefix: /admin/{_locale}
    type: annotation
    host: '%admin_domain%'
    defaults:
        _locale: zh_CN
        path: /admin/zh_CN
    requirements:
        _locale: '%app_locales%'

admin_login:
    path: /login
    host: '%admin_domain%'
    controller: App\Controller\Admin\SecurityController::login

admin_logout:
    path: /logout
    host: '%admin_domain%'
    controller: App\Controller\Admin\SecurityController::logout