easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    prefix: /{_locale}/admin
    type: annotation
    defaults:
        _locale: zh_CN
        path: /zh_CN/admin
    requirements:
        _locale: '%app_locales%'
